### ISSUE TITLE
Global typo

### ISSUE THREAD

**Issue by pombredanne** [artloder/icanhasfile#1]
I think there is a typo in the name of this package and therefore in file names and some variable and function names and various documentation: `has` is spelled `haz`.  So it should be `icanhazfile`.
U can c some examples of this proper spelling here: http://www.baggers.com/i-can-haz-lolcat-tips/

**Comment by artloder** [comment]
I think `has` is more common than `haz`. Examples:
- 634,000 "i can has" results vs 494,000 "i can haz" results in Google search
- https://en.wikipedia.org/wiki/I_Can_Has_Cheezburger%3F
- http://speaklolcat.com/?from=CAN+I+HAVE+A+CHEESEBURGER%3F
